### ISSUE TITLE
Request to publish this in hex.pm

### ISSUE THREAD

**Issue by handnot2** [KonnexionsGmbH/esaml#5]
It would be great to have esaml published on hex.pm so other hex.pm libs can leverage it. Thanks.

**Comment by handnot2** [comment]
Sorry for the delayed update.

* Created a fork from the original and pulled in changes from couple of other forks
   https://github.com/handnot2/esaml
* Created a corresponding Hex package from this git repo
   https://hex.pm/packages/esaml

I understand this may not be optimal. I will be glad to handoff the ownership for these if that is desirable.

**Comment by acautin** [comment]
@handnot2 thanks for making this package available in the hex ecosystem, we are not the original authors of this library and our fork is for our internal purpose only so it might have things that are not generic enough, but if you find things that are useful and you want to include in your published library that is cool too.

Cheers
Agustin.
